# Generated by Django 6.0.2 on 2026-04-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato_nome', models.CharField(blank=True, default='', max_length=150)),
                ('empresa', models.CharField(blank=True, default='', max_length=150)),
                ('canal_origem', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('email', 'E-mail'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('conteudo', models.TextField()),
                ('categoria', models.CharField(blank=True, choices=[('duvida', 'Duvida'), ('comercial', 'Comercial'), ('suporte', 'Suporte'), ('financeiro', 'Financeiro'), ('agendamento', 'Agendamento'), ('outro', 'Outro')], default='', max_length=20)),
                ('urgencia', models.CharField(blank=True, choices=[('baixa', 'Baixa'), ('media', 'Media'), ('alta', 'Alta')], default='', max_length=10)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('triado', 'Triado'), ('aguardando_resposta', 'Aguardando resposta'), ('resolvido', 'Resolvido')], default='novo', max_length=30)),
                ('tags', models.CharField(blank=True, default='', help_text='Lista simples de tags separadas por virgula.', max_length=255)),
                ('sugestao_proxima_acao', models.TextField(blank=True, default='')),
                ('sugestao_resposta', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inbox item',
                'verbose_name_plural': 'Inbox items',
                'ordering': ['-created_at'],
            },
        ),
    ]
