# Generated by Django 6.0.2 on 2026-04-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxitem',
            name='sugestao_categoria',
            field=models.CharField(blank=True, choices=[('duvida', 'Duvida'), ('comercial', 'Comercial'), ('suporte', 'Suporte'), ('financeiro', 'Financeiro'), ('agendamento', 'Agendamento'), ('outro', 'Outro')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='inboxitem',
            name='sugestao_urgencia',
            field=models.CharField(blank=True, choices=[('baixa', 'Baixa'), ('media', 'Media'), ('alta', 'Alta')], default='', max_length=10),
        ),
    ]
